<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>MessageApp</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MessageApp.Domain\MessageApp.Domain.csproj" />
    <ProjectReference Include="..\MessageApp.Application.Contracts\MessageApp.Application.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.PermissionManagement.Application" Version="10.4.0" />
    <PackageReference Include="Volo.Abp.FeatureManagement.Application" Version="10.4.0" />
    <PackageReference Include="Volo.Abp.SettingManagement.Application" Version="10.4.0" />
    <PackageReference Include="Volo.Abp.Account.Application" Version="10.4.0" />
    <PackageReference Include="Volo.Abp.Identity.Application" Version="10.4.0" />
    <PackageReference Include="Volo.Abp.TenantManagement.Application" Version="10.4.0" />
  </ItemGroup>

</Project>
